version: "3.1"

services:
  http:
    container_name: "http_pr"
    build:
      context: "./"
      dockerfile: "./docker/http.Dockerfile"
    ports:
      - "8085:8085"
    links:
      - "grpc:grpc"
    environment:
      PORT: ":8085"
      GRPC: "grpc:9000"

  grpc:
    container_name: "grpc"
    build:
      context: "./"
      dockerfile: "./docker/grpc.Dockerfile"
    ports:
      - "9000:9000"
    environment:
      TCP_PORT: ":9000"
      DB_TYPE: "postgres"
      REDIS_ADDR: "redis:6379"
      REDIS_DB: "redisDB"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "postgres"
      POSTGRES_SSL: "disable"
#    depends_on:
#      - postgres

  redis:
    container_name: "redis"
    image: redis

  postgres:
    container_name: "postgres"
    image: postgres:latest
    restart: always
    user: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DATABASE: "postgres"
    volumes:
      - ./storage/postgres/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"