// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Author  string `json:"author"`
	Message string `json:"message"`
}

type Post struct {
	ID      string `json:"id"`
	Author  string `json:"author"`
	Message string `json:"message"`
}

type UpdatePost struct {
	ID      string  `json:"id"`
	Author  *string `json:"author"`
	Message *string `json:"message"`
}
