apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-grpc-deployment
  labels:
    app: http-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-grpc
  template:
    metadata:
      labels:
        app: http-grpc
    spec:
      containers:
        - name: http-grpc
          image: stasbigunenko/http_grpc
          env:
            - name: TCP_PORT
              value: ":9000"
            - name: DB_TYPE
              value: "redis"
            - name: REDIS_ADDR
              value: "redis-service:6379"
            - name: REDIS_DB
              value: "redisDB"
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_HOST
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "qwerty"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_SSL
              value: "disable"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "root"
            - name: MONGO_ADDR
              value: "mongo-service:27017"
            - name: ELK_ADDR
              value: "elk-service:9200"
          ports:
            - containerPort: 9000