apiVersion: v1
kind: Service
metadata:
  name: http-monitor-svc
  labels:
    app: http-http
    release: stable
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/path: /posts/metrics
    prometheus.io/port: "8085"
  namespace: default
spec:
  ports:
    - name: http-http
      port: 8085
      protocol: TCP
  selector:
    app: http-http
    release: stable