apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-http-deployment
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /posts/metrics
    prometheus.io/port: "8085"
  labels:
    app: http-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-http
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /posts/metrics
        prometheus.io/port: "8085"
      labels:
        app: http-http
        release: stable
    spec:
      containers:
        - name: http-http
          image: stasbigunenko/http_http
          env:
            - name: PORT_HTTP
              value: ":8085"
            - name: GRPC
              value: "grpc-service:9000"
          ports:
            - containerPort: 8085